### ISSUE TITLE
X & Y Overflow

### ISSUE THREAD

**Issue by 9ggy** [grilme99/grilme99.github.io#2]
## **There are both x and y overflows on the gril.me homepage**
![image](https://user-images.githubusercontent.com/84878036/150163637-7ae55a17-de49-4669-b06f-1c35c5d68881.png)

## Solution

I would recommend hiding the x and y overflow on the webpage by replacing your `body` element with this code:
```css
body {
  /* Your normal code */
  margin: 0;
  padding: 0;
  font-family: 'Nunito', sans-serif;
  color: #121212;
  /* Hiding the x and y overflow */
  overflow-x: hidden;
  overflow-y: hidden;
}
```
